erDiagram


PRODUTOS {
Numeric ID_PRODUTO PK "NOT NULL"
Varchar2 NOME_PRODUTO "NOT NULL"
Varchar2 DESCRICAO "NULL"
Numeric PRECO "NOT NULL"
Numeric ESTOQUE_ATUAL "NOT NULL"
}

%% TIPO == ENTRADA OU SAIDA
PEDIDOS {
Numeric ID_PEDIDO PK     "NOT NULL"
Varchar2 nome_produto  FK "NOT NULL"
Numeric ID_PRODUTO    FK "NOT NULL"
Date DATA                "NOT NULL"
Varchar2 TIPO            "NOT NULL"
Numeric QUANTIDADE       "NOT NULL"
}


PEDIDOS }|--|| PRODUTOS : ""