erDiagram


PRODUTOS {
Numeric ID_PRODUTO PK "NOT NULL"
Varchar2 NOME_PRODUTO "NOT NULL"
Varchar2 DESCRICAO "NULL"
Numeric PRECO "NOT NULL"
Numeric ESTOQUE_ATUAL "NOT NULL"
}

FORNECEDORES {
Numeric ID_FORNECEDOR PK "NOT NULL"
varchar NOME_FORNECEDOR "NOT NULL"
varchar CEP "NULL"
varchar EMAIL "NULL"
}

ALMOXARIFE {
Numeric ID_ALMOXARIFE PK "NOT NULL"
varchar2 NOME "NOT NULL"
varchar2 CEP "NULL"
varchar2 EMAIL "NULL"
}

%% TIPO == ENTRADA OU SAIDA
PEDIDOS {
Numeric ID_PEDIDO PK     "NOT NULL"
Date DATA                "NOT NULL"
Varchar2 TIPO            "NOT NULL"
Numeric ID_PRODUTO    FK "NOT NULL"
Numeric ID_FORNECEDOR FK "NULL"
Numeric ID_ALMOXARIFE FK "NULL"
Numeric QUANTIDADE       "NOT NULL"
}

ITENS_PEDIDO {
Numeric ID_PRODUTO FK "NOT NULL"
Numeric ID_PEDIDO FK "NOT NULL"
Numeric QUANTIDADE "NOT NULL"
}

PAGAMENTOS {
Numeric ID_PAGAMENTO PK "NOT NULL"
DATE DATA "NOT NULL"
DATE HORA "NOT NULL"
Numeric VALOR "NOT NULL"
Numeric ID_PEDIDO FK "NOT NULL"
}

FORNECEDORES ||--o{ PEDIDOS : ""
ALMOXARIFE ||--o{ PEDIDOS : ""
PEDIDOS ||--o{ ITENS_PEDIDO : ""
PRODUTOS ||--o{ ITENS_PEDIDO : ""
PEDIDOS ||--|| PAGAMENTOS : ""