CREATE TABLE PRODUTOS (
    ID_PRODUTO NUMBER NOT NULL PRIMARY KEY,
    NOME_PRODUTO VARCHAR2(80) NOT NULL,
    DESCRICAO VARCHAR2(200) NULL,
    PRECO NUMBER(10,2) NULL,
    ESTOQUE_ATUAL NUMBER NOT NULL
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO NUMBER NOT NULL PRIMARY KEY,
    DATA DATE NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    ID_PRODUTO NUMBER NOT NULL,
    ID_FORNECEDOR NUMBER NULL,
    ID_COMPRADOR NUMBER NULL,
    QUANTIDADE NUMBER NOT NULL
);