    /* Apaga relacionamentos, tabelas e sequences */
    ALTER TABLE PEDIDOS DROP CONSTRAINT FK_PEDIDOS_PRODUTOS;
    DROP TABLE PEDIDOS CASCADE CONSTRAINTS;
    DROP TABLE PRODUTOS CASCADE CONSTRAINTS;

    /* Create Sequence */
    DROP SEQUENCE PRODUTOS_ID_PRODUTO_SEQ;
    CREATE SEQUENCE PRODUTOS_ID_PRODUTO_SEQ START WITH 11;

    DROP SEQUENCE PEDIDOS_ID_PEDIDO_SEQ;
    CREATE SEQUENCE PEDIDOS_ID_PEDIDO_SEQ START WITH 16;


    /* Cria tabelas */
    CREATE TABLE PRODUTOS (
        ID_PRODUTO NUMBER NOT NULL PRIMARY KEY,
        NOME_PRODUTO VARCHAR2(80) NOT NULL,
        DESCRICAO VARCHAR2(200) NULL,
        PRECO NUMBER(10,2) NULL,
        ESTOQUE_ATUAL NUMBER NOT NULL
    );

    CREATE TABLE PEDIDOS (
        ID_PEDIDO NUMBER NOT NULL PRIMARY KEY,
        DATA DATE NOT NULL,
        TIPO VARCHAR2(10) NOT NULL,
        ID_PRODUTO NUMBER NOT NULL,
        QUANTIDADE NUMBER NOT NULL,
        CONSTRAINT FK_PEDIDOS_PRODUTOS
            FOREIGN KEY (ID_PRODUTO)
            REFERENCES PRODUTOS(ID_PRODUTO)
    );