INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (1, 'Teclado USB', 'Teclado padrão ABNT2', 79.90, 50);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (2, 'Mouse Sem Fio', 'Mouse óptico com receptor USB', 59.50, 70);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (3, 'Monitor 24"', 'Monitor Full HD 24 polegadas', 899.00, 20);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (4, 'Headset Gamer', 'Fone com microfone e RGB', 249.99, 35);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (5, 'SSD 480GB', 'SSD SATA 480GB', 329.00, 40);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (6, 'Cabo HDMI', 'Cabo HDMI 2 metros', 29.90, 100);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (7, 'Pendrive 32GB', 'USB 3.0 32GB', 45.00, 80);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (8, 'Fonte 500W', 'Fonte ATX 500W certificada', 299.00, 15);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (9, 'Placa de Vídeo 4GB', 'GPU 4GB dedicada', 1499.00, 10);
INSERT INTO PRODUTOS (ID_PRODUTO, NOME_PRODUTO, DESCRICAO, PRECO, ESTOQUE_ATUAL) VALUES (10, 'Notebook i5', 'Notebook com 8GB RAM e SSD', 3499.00, 5);

COMMIT;

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (1, TO_DATE('2025-01-10', 'YYYY-MM-DD'), 'COMPRA', 1, NULL, NULL, 5);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (2, TO_DATE('2025-01-11', 'YYYY-MM-DD'), 'VENDA', 2, NULL, NULL, 3);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (3, TO_DATE('2025-01-12', 'YYYY-MM-DD'), 'COMPRA', 3, NULL, NULL, 2);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (4, TO_DATE('2025-01-13', 'YYYY-MM-DD'), 'VENDA', 4, NULL, NULL, 4);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (5, TO_DATE('2025-01-14', 'YYYY-MM-DD'), 'COMPRA', 5, NULL, NULL, 1);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (6, TO_DATE('2025-01-15', 'YYYY-MM-DD'), 'VENDA', 6, NULL, NULL, 10);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (7, TO_DATE('2025-01-16', 'YYYY-MM-DD'), 'COMPRA', 7, NULL, NULL, 8);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (8, TO_DATE('2025-01-17', 'YYYY-MM-DD'), 'VENDA', 8, NULL, NULL, 2);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (9, TO_DATE('2025-01-18', 'YYYY-MM-DD'), 'COMPRA', 9, NULL, NULL, 1);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA, TIPO, ID_PRODUTO, ID_FORNECEDOR, ID_COMPRADOR, QUANTIDADE)
VALUES (10, TO_DATE('2025-01-19', 'YYYY-MM-DD'), 'VENDA', 10, NULL, NULL, 1);

COMMIT;